#!/usr/bin/env perl

use strict;
use warnings;

use version; our $VERSION = qv('1.0.0');

use utf8;
use open qw(:std :utf8);
use Carp;
use Cwd qw(abs_path getcwd);
use English qw(-no_match_vars);
use File::Basename;
use File::Spec;
use Getopt::Long;
use Pod::Usage;

my ( $script_name, $script_folder ) = fileparse( abs_path($PROGRAM_NAME) );
my $current_folder = getcwd();

my ( $help, $man );

GetOptions(
    'help!'        => \$help,
    'man!'         => \$man,
) or pod2usage( -verbose => 1, -exit => 1 );

# add other options to check for here
if( defined $help ) {
    pod2usage( -verbose => 1, -exit => 0 );
}
if( defined $man ) {
    pod2usage( -verbose => 2, -exit => 0 );
}

# Main script body here

exit 0;
__END__
=head1 NAME

 pl

=head1 DESCRIPTION

 This is some placeholder text for my actual description.

=head1 USAGE

 pl Arguments options etc

=head1 ARGUMENTS

 --help  Print this help text

=head1 OPTIONS

 This is some placeholder text for options

=cut
# vim:fdm=marker:syntax=perl:cc=80:fenc=utf-8
