#!/usr/bin/env perl

use strict;
use warnings;

use version; our $VERSION = qv('1.0.0');

use Carp;
use Cwd qw(abs_path getcwd);
use English qw(-no_match_vars);
use File::Basename;
use File::Spec;
use Getopt::Long;

my ( $script_name, $script_folder ) = fileparse( abs_path($PROGRAM_NAME) );
my $current_folder = getcwd();

my ( $help );

GetOptions(
    'help'        => \$help,
    'h'           => \$help,
);

# add other options to check for here
if( defined $help ) {
    HELP_MESSAGE();
    if( defined( $help ) ) {
        exit 0;
    }
    exit 1;
}

# Main script body here


exit 0;

sub HELP_MESSAGE {
    my $helptext;
    my $name_length = length $script_name;

    $helptext = "Usage:\n";
    $helptext .= q{  }.$script_name."\n";

    print {*STDERR} $helptext;
    return;
}
# vim:fdm=marker:syntax=perl:cc=80
